"""empty message

Revision ID: 32b906f09957
Revises: 5b919f388a78
Create Date: 2025-02-06 10:56:38.923563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32b906f09957'
down_revision = '5b919f388a78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_template', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burger', schema=None) as batch_op:
        batch_op.drop_column('is_template')

    # ### end Alembic commands ###
