"""empty message

Revision ID: 5b919f388a78
Revises: af102449b084
Create Date: 2025-02-04 14:32:51.333117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b919f388a78'
down_revision = 'af102449b084'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burger', schema=None) as batch_op:
        batch_op.alter_column('pickles',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('lettuce',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.alter_column('tomato',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burger', schema=None) as batch_op:
        batch_op.alter_column('tomato',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('lettuce',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('pickles',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
