"""empty message

Revision ID: af102449b084
Revises: cfb70fd50622
Create Date: 2025-02-04 14:28:27.479233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af102449b084'
down_revision = 'cfb70fd50622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burger', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sauce', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('pickles', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('lettuce', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('tomato', sa.String(length=200), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('burger', schema=None) as batch_op:
        batch_op.drop_column('tomato')
        batch_op.drop_column('lettuce')
        batch_op.drop_column('pickles')
        batch_op.drop_column('sauce')

    # ### end Alembic commands ###
