"""empty message

Revision ID: cfb70fd50622
Revises: ad1fe30cfd31
Create Date: 2025-02-04 11:24:59.894445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfb70fd50622'
down_revision = 'ad1fe30cfd31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('burger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('top_bun', sa.String(length=200), nullable=False),
    sa.Column('meat', sa.String(length=200), nullable=False),
    sa.Column('cheese', sa.String(length=200), nullable=False),
    sa.Column('bottom_bun', sa.String(length=200), nullable=False),
    sa.Column('spoon_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('burger')
    # ### end Alembic commands ###
